### ISSUE TITLE
starter-css?

### ISSUE THREAD

**Issue by berot3** [wilhelmer/mkdocs-add-teaser#1]
Hi! thanks a lot but how about we put some css-suggwstions here to get started with?

only `font-weight: bold;` should not be the only end-result right?

I am using mkdocs-material so I am wondering what css I could use so that the teaser really pop out but still fits into the theme? Any suggestions?

I will try to find something, but since I am a css-noob I would not wait too long... sorry.

**Comment by wilhelmer** [comment]
Sure. The plugin only adds the class, so you can style it however you want. 

Using bold is the common way news websites etc. handle teaser text. I can’t think of anything else right now — maybe you can describe what you have in mind and I translate it into CSS for you? 

If there are useful alternatives, I‘ll add them as examples to readme.txt.

**Comment by berot3** [comment]
Well I pictured something like this: https://images.app.goo.gl/J1y9FYyrbwTy46kU7
But the large first letter is maybe too blog-style :)

So I would definitly make the font larger. Maybe use  a dark-grey or light-grey font-color? 

It's hard to find something though.... :D 

What do you think?

**Comment by wilhelmer** [comment]
Added some examples to `README.md`. 

See https://github.com/wilhelmer/mkdocs-add-teaser/
